var searchData=
[
  ['kudu_20c_2b_2b_20client_20api_20documentation',['Kudu C++ client API documentation',['../index.html',1,'']]],
  ['keepalive',['KeepAlive',['../classkudu_1_1client_1_1_kudu_scanner.html#aa4a0caf7142880255d7aac1d75f33d21',1,'kudu::client::KuduScanner']]],
  ['knotimestamp',['kNoTimestamp',['../classkudu_1_1client_1_1_kudu_client.html#a196f1a18c000cdca309d05161caaddaa',1,'kudu::client::KuduClient']]],
  ['kudu_5fcheck_5fok',['KUDU_CHECK_OK',['../status_8h.html#ac503ba85e942147294cdc82087da60f6',1,'status.h']]],
  ['kudu_5fcheck_5fok_5fprepend',['KUDU_CHECK_OK_PREPEND',['../status_8h.html#a706c9f6ef1715b8f7a9185fb3c247d3f',1,'status.h']]],
  ['kudu_5fdcheck_5fok',['KUDU_DCHECK_OK',['../status_8h.html#a99332afa18f00de3c7fcf3e76949df9d',1,'status.h']]],
  ['kudu_5fdcheck_5fok_5fprepend',['KUDU_DCHECK_OK_PREPEND',['../status_8h.html#a2b360b53025724bb97d1dc21e25e26cc',1,'status.h']]],
  ['kudu_5flog_5fand_5freturn',['KUDU_LOG_AND_RETURN',['../status_8h.html#abbd85cc2c5535627091bb06a21918150',1,'status.h']]],
  ['kudu_5freturn_5fnot_5fok',['KUDU_RETURN_NOT_OK',['../status_8h.html#a0de56a3f0e9d83b8ffdd63eac83c54ab',1,'status.h']]],
  ['kudu_5freturn_5fnot_5fok_5feval',['KUDU_RETURN_NOT_OK_EVAL',['../status_8h.html#a8fd1f0d6a9b2457c18e218d3540c4b3e',1,'status.h']]],
  ['kudu_5freturn_5fnot_5fok_5flog',['KUDU_RETURN_NOT_OK_LOG',['../status_8h.html#af09a6a2eca53c9424d74c7fd9f39c5ce',1,'status.h']]],
  ['kudu_5freturn_5fnot_5fok_5fprepend',['KUDU_RETURN_NOT_OK_PREPEND',['../status_8h.html#af66b8458f1d3f1264c1da86744e29e46',1,'status.h']]],
  ['kudu_5freturn_5fnot_5fok_5fret',['KUDU_RETURN_NOT_OK_RET',['../status_8h.html#a58d31c81bf1101a3ead737e9a4a4f223',1,'status.h']]],
  ['kudu_5fwarn_5fnot_5fok',['KUDU_WARN_NOT_OK',['../status_8h.html#a1e64fec5ef85c0c738f6ac3f398f607e',1,'status.h']]],
  ['kuduclient',['KuduClient',['../classkudu_1_1client_1_1_kudu_client.html',1,'kudu::client']]],
  ['kuduclientbuilder',['KuduClientBuilder',['../classkudu_1_1client_1_1_kudu_client_builder.html',1,'kudu::client']]],
  ['kuducolumnschema',['KuduColumnSchema',['../classkudu_1_1client_1_1_kudu_column_schema.html',1,'kudu::client::KuduColumnSchema'],['../classkudu_1_1client_1_1_kudu_column_schema.html#afc82e98af83ba61079ba5d30401b5872',1,'kudu::client::KuduColumnSchema::KuduColumnSchema()']]],
  ['kuducolumnspec',['KuduColumnSpec',['../classkudu_1_1client_1_1_kudu_column_spec.html',1,'kudu::client']]],
  ['kuducolumnstorageattributes',['KuduColumnStorageAttributes',['../classkudu_1_1client_1_1_kudu_column_storage_attributes.html',1,'kudu::client::KuduColumnStorageAttributes'],['../classkudu_1_1client_1_1_kudu_column_storage_attributes.html#a2d6e5bec50a7305b3b4d75d21d000fab',1,'kudu::client::KuduColumnStorageAttributes::KuduColumnStorageAttributes()']]],
  ['kuducolumntypeattributes',['KuduColumnTypeAttributes',['../classkudu_1_1client_1_1_kudu_column_type_attributes.html',1,'kudu::client::KuduColumnTypeAttributes'],['../classkudu_1_1client_1_1_kudu_column_type_attributes.html#afdfe9a35df0360457583e303fdfe3eae',1,'kudu::client::KuduColumnTypeAttributes::KuduColumnTypeAttributes(const KuduColumnTypeAttributes &amp;other)'],['../classkudu_1_1client_1_1_kudu_column_type_attributes.html#abbdc4a2daa6ee10ee57cb6258bc996f4',1,'kudu::client::KuduColumnTypeAttributes::KuduColumnTypeAttributes(int8_t precision, int8_t scale)']]],
  ['kududelete',['KuduDelete',['../classkudu_1_1client_1_1_kudu_delete.html',1,'kudu::client']]],
  ['kuduerror',['KuduError',['../classkudu_1_1client_1_1_kudu_error.html',1,'kudu::client']]],
  ['kuduinsert',['KuduInsert',['../classkudu_1_1client_1_1_kudu_insert.html',1,'kudu::client']]],
  ['kuduloggingcallback',['KuduLoggingCallback',['../classkudu_1_1client_1_1_kudu_logging_callback.html',1,'kudu::client']]],
  ['kuduloggingfunctioncallback',['KuduLoggingFunctionCallback',['../classkudu_1_1client_1_1_kudu_logging_function_callback.html',1,'kudu::client::KuduLoggingFunctionCallback&lt; T &gt;'],['../classkudu_1_1client_1_1_kudu_logging_function_callback.html#a4263c504b21e0e5827f47a902e908a2c',1,'kudu::client::KuduLoggingFunctionCallback::KuduLoggingFunctionCallback()']]],
  ['kuduloggingmembercallback',['KuduLoggingMemberCallback',['../classkudu_1_1client_1_1_kudu_logging_member_callback.html',1,'kudu::client::KuduLoggingMemberCallback&lt; T &gt;'],['../classkudu_1_1client_1_1_kudu_logging_member_callback.html#aeda4119b1288db0d055c9800e3485fd8',1,'kudu::client::KuduLoggingMemberCallback::KuduLoggingMemberCallback()']]],
  ['kudupartialrow',['KuduPartialRow',['../class_kudu_partial_row.html',1,'KuduPartialRow'],['../class_kudu_partial_row.html#a9eb1cbd1b216f6313a03c82ab67112e4',1,'KuduPartialRow::KuduPartialRow(const Schema *schema)'],['../class_kudu_partial_row.html#ab4ebb399982edbb3e877e38a74c700f1',1,'KuduPartialRow::KuduPartialRow(const KuduPartialRow &amp;other)']]],
  ['kudupartitioner',['KuduPartitioner',['../classkudu_1_1client_1_1_kudu_partitioner.html',1,'kudu::client']]],
  ['kudupartitionerbuilder',['KuduPartitionerBuilder',['../classkudu_1_1client_1_1_kudu_partitioner_builder.html',1,'kudu::client::KuduPartitionerBuilder'],['../classkudu_1_1client_1_1_kudu_partitioner_builder.html#a27d130235be1c2691779e1d97732a4ba',1,'kudu::client::KuduPartitionerBuilder::KuduPartitionerBuilder()']]],
  ['kudupredicate',['KuduPredicate',['../classkudu_1_1client_1_1_kudu_predicate.html',1,'kudu::client']]],
  ['kudureplica',['KuduReplica',['../classkudu_1_1client_1_1_kudu_replica.html',1,'kudu::client']]],
  ['kuduscanbatch',['KuduScanBatch',['../classkudu_1_1client_1_1_kudu_scan_batch.html',1,'kudu::client']]],
  ['kuduscanner',['KuduScanner',['../classkudu_1_1client_1_1_kudu_scanner.html',1,'kudu::client::KuduScanner'],['../classkudu_1_1client_1_1_kudu_scanner.html#a2c621f778072a02f4092e96a0baf8180',1,'kudu::client::KuduScanner::KuduScanner()']]],
  ['kuduscantoken',['KuduScanToken',['../classkudu_1_1client_1_1_kudu_scan_token.html',1,'kudu::client']]],
  ['kuduscantokenbuilder',['KuduScanTokenBuilder',['../classkudu_1_1client_1_1_kudu_scan_token_builder.html',1,'kudu::client::KuduScanTokenBuilder'],['../classkudu_1_1client_1_1_kudu_scan_token_builder.html#aa8d300b560d419030abd503b66812484',1,'kudu::client::KuduScanTokenBuilder::KuduScanTokenBuilder()']]],
  ['kuduschema',['KuduSchema',['../classkudu_1_1client_1_1_kudu_schema.html',1,'kudu::client::KuduSchema'],['../classkudu_1_1client_1_1_kudu_schema.html#a41a683f3d93357fe68531bf71df39d02',1,'kudu::client::KuduSchema::KuduSchema()']]],
  ['kuduschemabuilder',['KuduSchemaBuilder',['../classkudu_1_1client_1_1_kudu_schema_builder.html',1,'kudu::client']]],
  ['kudusession',['KuduSession',['../classkudu_1_1client_1_1_kudu_session.html',1,'kudu::client']]],
  ['kudustatuscallback',['KuduStatusCallback',['../classkudu_1_1client_1_1_kudu_status_callback.html',1,'kudu::client']]],
  ['kudustatusfunctioncallback',['KuduStatusFunctionCallback',['../classkudu_1_1client_1_1_kudu_status_function_callback.html',1,'kudu::client::KuduStatusFunctionCallback&lt; T &gt;'],['../classkudu_1_1client_1_1_kudu_status_function_callback.html#aca289bbf6ad9720bd74a90550f6c9b3b',1,'kudu::client::KuduStatusFunctionCallback::KuduStatusFunctionCallback()']]],
  ['kudustatusmembercallback',['KuduStatusMemberCallback',['../classkudu_1_1client_1_1_kudu_status_member_callback.html',1,'kudu::client::KuduStatusMemberCallback&lt; T &gt;'],['../classkudu_1_1client_1_1_kudu_status_member_callback.html#acdb02b9798adf2c80b39cfb024f199aa',1,'kudu::client::KuduStatusMemberCallback::KuduStatusMemberCallback()']]],
  ['kudutable',['KuduTable',['../classkudu_1_1client_1_1_kudu_table.html',1,'kudu::client']]],
  ['kudutablealterer',['KuduTableAlterer',['../classkudu_1_1client_1_1_kudu_table_alterer.html',1,'kudu::client']]],
  ['kudutablecreator',['KuduTableCreator',['../classkudu_1_1client_1_1_kudu_table_creator.html',1,'kudu::client']]],
  ['kudutablet',['KuduTablet',['../classkudu_1_1client_1_1_kudu_tablet.html',1,'kudu::client']]],
  ['kudutabletserver',['KuduTabletServer',['../classkudu_1_1client_1_1_kudu_tablet_server.html',1,'kudu::client']]],
  ['kuduupdate',['KuduUpdate',['../classkudu_1_1client_1_1_kudu_update.html',1,'kudu::client']]],
  ['kuduupsert',['KuduUpsert',['../classkudu_1_1client_1_1_kudu_upsert.html',1,'kudu::client']]],
  ['kuduvalue',['KuduValue',['../classkudu_1_1client_1_1_kudu_value.html',1,'kudu::client']]],
  ['kuduwriteoperation',['KuduWriteOperation',['../classkudu_1_1client_1_1_kudu_write_operation.html',1,'kudu::client']]]
];
