var annotated_dup =
[
    [ "kudu", null, [
      [ "client", null, [
        [ "internal", null, [
          [ "AsyncLeaderMasterRpc", "classkudu_1_1client_1_1internal_1_1AsyncLeaderMasterRpc.html", null ],
          [ "AsyncRandomTxnManagerRpc", "classkudu_1_1client_1_1internal_1_1AsyncRandomTxnManagerRpc.html", null ]
        ] ],
        [ "KuduBloomFilter", "classkudu_1_1client_1_1KuduBloomFilter.html", "classkudu_1_1client_1_1KuduBloomFilter" ],
        [ "KuduBloomFilterBuilder", "classkudu_1_1client_1_1KuduBloomFilterBuilder.html", "classkudu_1_1client_1_1KuduBloomFilterBuilder" ],
        [ "KuduClient", "classkudu_1_1client_1_1KuduClient.html", "classkudu_1_1client_1_1KuduClient" ],
        [ "KuduClientBuilder", "classkudu_1_1client_1_1KuduClientBuilder.html", "classkudu_1_1client_1_1KuduClientBuilder" ],
        [ "KuduColumnarScanBatch", "classkudu_1_1client_1_1KuduColumnarScanBatch.html", "classkudu_1_1client_1_1KuduColumnarScanBatch" ],
        [ "KuduColumnSchema", "classkudu_1_1client_1_1KuduColumnSchema.html", "classkudu_1_1client_1_1KuduColumnSchema" ],
        [ "KuduColumnSpec", "classkudu_1_1client_1_1KuduColumnSpec.html", "classkudu_1_1client_1_1KuduColumnSpec" ],
        [ "KuduColumnStorageAttributes", "classkudu_1_1client_1_1KuduColumnStorageAttributes.html", "classkudu_1_1client_1_1KuduColumnStorageAttributes" ],
        [ "KuduColumnTypeAttributes", "classkudu_1_1client_1_1KuduColumnTypeAttributes.html", "classkudu_1_1client_1_1KuduColumnTypeAttributes" ],
        [ "KuduDelete", "classkudu_1_1client_1_1KuduDelete.html", "classkudu_1_1client_1_1KuduDelete" ],
        [ "KuduDeleteIgnore", "classkudu_1_1client_1_1KuduDeleteIgnore.html", "classkudu_1_1client_1_1KuduDeleteIgnore" ],
        [ "KuduError", "classkudu_1_1client_1_1KuduError.html", "classkudu_1_1client_1_1KuduError" ],
        [ "KuduInsert", "classkudu_1_1client_1_1KuduInsert.html", "classkudu_1_1client_1_1KuduInsert" ],
        [ "KuduInsertIgnore", "classkudu_1_1client_1_1KuduInsertIgnore.html", "classkudu_1_1client_1_1KuduInsertIgnore" ],
        [ "KuduLoggingCallback", "classkudu_1_1client_1_1KuduLoggingCallback.html", "classkudu_1_1client_1_1KuduLoggingCallback" ],
        [ "KuduLoggingFunctionCallback", "classkudu_1_1client_1_1KuduLoggingFunctionCallback.html", "classkudu_1_1client_1_1KuduLoggingFunctionCallback" ],
        [ "KuduLoggingMemberCallback", "classkudu_1_1client_1_1KuduLoggingMemberCallback.html", "classkudu_1_1client_1_1KuduLoggingMemberCallback" ],
        [ "KuduPartitioner", "classkudu_1_1client_1_1KuduPartitioner.html", "classkudu_1_1client_1_1KuduPartitioner" ],
        [ "KuduPartitionerBuilder", "classkudu_1_1client_1_1KuduPartitionerBuilder.html", "classkudu_1_1client_1_1KuduPartitionerBuilder" ],
        [ "KuduPredicate", "classkudu_1_1client_1_1KuduPredicate.html", "classkudu_1_1client_1_1KuduPredicate" ],
        [ "KuduRangePartition", "classkudu_1_1client_1_1KuduRangePartition.html", "classkudu_1_1client_1_1KuduRangePartition" ],
        [ "KuduReplica", "classkudu_1_1client_1_1KuduReplica.html", "classkudu_1_1client_1_1KuduReplica" ],
        [ "KuduScanBatch", "classkudu_1_1client_1_1KuduScanBatch.html", "classkudu_1_1client_1_1KuduScanBatch" ],
        [ "KuduScanner", "classkudu_1_1client_1_1KuduScanner.html", "classkudu_1_1client_1_1KuduScanner" ],
        [ "KuduScanToken", "classkudu_1_1client_1_1KuduScanToken.html", "classkudu_1_1client_1_1KuduScanToken" ],
        [ "KuduScanTokenBuilder", "classkudu_1_1client_1_1KuduScanTokenBuilder.html", "classkudu_1_1client_1_1KuduScanTokenBuilder" ],
        [ "KuduSchema", "classkudu_1_1client_1_1KuduSchema.html", "classkudu_1_1client_1_1KuduSchema" ],
        [ "KuduSchemaBuilder", "classkudu_1_1client_1_1KuduSchemaBuilder.html", "classkudu_1_1client_1_1KuduSchemaBuilder" ],
        [ "KuduSession", "classkudu_1_1client_1_1KuduSession.html", "classkudu_1_1client_1_1KuduSession" ],
        [ "KuduStatusCallback", "classkudu_1_1client_1_1KuduStatusCallback.html", "classkudu_1_1client_1_1KuduStatusCallback" ],
        [ "KuduStatusFunctionCallback", "classkudu_1_1client_1_1KuduStatusFunctionCallback.html", "classkudu_1_1client_1_1KuduStatusFunctionCallback" ],
        [ "KuduStatusMemberCallback", "classkudu_1_1client_1_1KuduStatusMemberCallback.html", "classkudu_1_1client_1_1KuduStatusMemberCallback" ],
        [ "KuduTable", "classkudu_1_1client_1_1KuduTable.html", "classkudu_1_1client_1_1KuduTable" ],
        [ "KuduTableAlterer", "classkudu_1_1client_1_1KuduTableAlterer.html", "classkudu_1_1client_1_1KuduTableAlterer" ],
        [ "KuduTableCreator", "classkudu_1_1client_1_1KuduTableCreator.html", "classkudu_1_1client_1_1KuduTableCreator" ],
        [ "KuduTableStatistics", "classkudu_1_1client_1_1KuduTableStatistics.html", "classkudu_1_1client_1_1KuduTableStatistics" ],
        [ "KuduTablet", "classkudu_1_1client_1_1KuduTablet.html", "classkudu_1_1client_1_1KuduTablet" ],
        [ "KuduTabletServer", "classkudu_1_1client_1_1KuduTabletServer.html", "classkudu_1_1client_1_1KuduTabletServer" ],
        [ "KuduTransaction", "classkudu_1_1client_1_1KuduTransaction.html", "classkudu_1_1client_1_1KuduTransaction" ],
        [ "KuduUpdate", "classkudu_1_1client_1_1KuduUpdate.html", "classkudu_1_1client_1_1KuduUpdate" ],
        [ "KuduUpdateIgnore", "classkudu_1_1client_1_1KuduUpdateIgnore.html", "classkudu_1_1client_1_1KuduUpdateIgnore" ],
        [ "KuduUpsert", "classkudu_1_1client_1_1KuduUpsert.html", "classkudu_1_1client_1_1KuduUpsert" ],
        [ "KuduUpsertIgnore", "classkudu_1_1client_1_1KuduUpsertIgnore.html", "classkudu_1_1client_1_1KuduUpsertIgnore" ],
        [ "KuduValue", "classkudu_1_1client_1_1KuduValue.html", "classkudu_1_1client_1_1KuduValue" ],
        [ "KuduWriteOperation", "classkudu_1_1client_1_1KuduWriteOperation.html", "classkudu_1_1client_1_1KuduWriteOperation" ],
        [ "ResourceMetrics", "classkudu_1_1client_1_1ResourceMetrics.html", "classkudu_1_1client_1_1ResourceMetrics" ]
      ] ],
      [ "internal_logging", null, [
        [ "CerrLog", "classkudu_1_1internal__logging_1_1CerrLog.html", "classkudu_1_1internal__logging_1_1CerrLog" ],
        [ "NullLog", "classkudu_1_1internal__logging_1_1NullLog.html", "classkudu_1_1internal__logging_1_1NullLog" ]
      ] ],
      [ "MonoDelta", "classkudu_1_1MonoDelta.html", "classkudu_1_1MonoDelta" ],
      [ "MonoTime", "classkudu_1_1MonoTime.html", "classkudu_1_1MonoTime" ],
      [ "Slice", "classkudu_1_1Slice.html", "classkudu_1_1Slice" ],
      [ "SliceMap", "structkudu_1_1SliceMap.html", "structkudu_1_1SliceMap" ],
      [ "Status", "classkudu_1_1Status.html", "classkudu_1_1Status" ]
    ] ],
    [ "KuduClient", "classKuduClient.html", "classKuduClient" ],
    [ "KuduClientBuilder", "classKuduClientBuilder.html", "classKuduClientBuilder" ],
    [ "KuduColumnSchema", "classKuduColumnSchema.html", "classKuduColumnSchema" ],
    [ "KuduDelete", "classKuduDelete.html", "classKuduDelete" ],
    [ "KuduError", "classKuduError.html", "classKuduError" ],
    [ "KuduInsert", "classKuduInsert.html", "classKuduInsert" ],
    [ "KuduPartialRow", "classKuduPartialRow.html", "classKuduPartialRow" ],
    [ "KuduPredicate", "classKuduPredicate.html", "classKuduPredicate" ],
    [ "KuduScanBatch", "classKuduScanBatch.html", "classKuduScanBatch" ],
    [ "KuduScanner", "classKuduScanner.html", "classKuduScanner" ],
    [ "KuduSchema", "classKuduSchema.html", "classKuduSchema" ],
    [ "KuduSchemaBuilder", "classKuduSchemaBuilder.html", "classKuduSchemaBuilder" ],
    [ "KuduSession", "classKuduSession.html", "classKuduSession" ],
    [ "KuduTable", "classKuduTable.html", "classKuduTable" ],
    [ "KuduTableAlterer", "classKuduTableAlterer.html", "classKuduTableAlterer" ],
    [ "KuduTableCreator", "classKuduTableCreator.html", "classKuduTableCreator" ],
    [ "KuduUpdate", "classKuduUpdate.html", "classKuduUpdate" ],
    [ "KuduValue", "classKuduValue.html", "classKuduValue" ],
    [ "KuduWriteOperation", "classKuduWriteOperation.html", "classKuduWriteOperation" ],
    [ "MonoDelta", "classMonoDelta.html", "classMonoDelta" ],
    [ "Status", "classStatus.html", "classStatus" ]
];