= Kudu Documentation

// tag::start_nav[]
++++
<!-- Static navbar -->
<div id="navigation_all">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Kudu Project</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="index.html">Home</a></li>
          <li><a href="overview.html">Overview</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Docs <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="introduction.html">Introducing Kudu</a></li>
              <li><a href="quickstart.html">Getting Started With Kudu</a></li>
              <li><a href="installation.html">Installation Guide</a></li>
              <li><a href="configuration.html">Configuring Kudu</a></li>
              <li><a href="administration.html">Administering Kudu</a></li>
              <li><a href="troubleshooting.html">Troubleshooting Kudu</a></li>
              <li><a href="developing.html">Developing Applications With Kudu</a></li>
              <li><a href="contributing.html">Contributing to Kudu</a></li>
              <li><a href="style_guide.html">Kudu Style Guide</a></li>
              <li><a href="configuration_reference.html">Kudu Configuration Reference</a></li>
              <li><a href="resources.html">Kudu Resources</a></li>
            </ul>
          </li>
          <li><a href="#">Repository</a></li>
          <li><a href="#">Contributions</a></li>
          <li><a href="community.html">Community</a></li>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>
</div>
++++
// end::start_nav[]

// License Header Here //
:author: Kudu Team
:imagesdir: ./images
:icons: font
:doctype: book
:backend: html5
:sectlinks:
:experimental:

++++
<div class="landing_page">
++++

link:introduction.html[Introducing Kudu]::
  Get familiar with what sets Kudu apart.

link:quickstart.html[Getting Started With Kudu]::
  Deploy a simple proof-of-concept Kudu cluster to try it out for yourself.

link:installation.html[Installation Guide]::
  Details about all the different options for installing Kudu.

link:configuration.html[Configuring Kudu]::
  Guidelines for customizing your Kudu cluster.

link:administration.html[Administering Kudu]::
  Keeping Kudu running smoothly.

link:troubleshooting.html[Troubleshooting Kudu]::
  Guidelines for solving problems with your Kudu cluster.

link:developing.html[Developing Applications With Kudu]::
  Information about Kudu APIs and links to working example code.

link:contributing.html[Contributing to Kudu]::
  Get involved in the Kudu community.

link:style_guide.html[Kudu Style Guide]::
  Guidelines for development and documentation contributions to the Kudu project.

link:configuration_reference.html[Kudu Configuration Reference]::
  Documentation for all Kudu configuration options.

link:resources.html[Kudu Resources]::
  Further reading about Kudu, columnar data stores, and other useful material for Kudu
  users and developers.

++++
</div>
++++
