= Kudu Documentation

// tag::start_nav[]
++++
<div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/index.html">Kudu Project</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="../index.html">Home</a></li>
              <li><a href="../overview.html">Overview</a></li>
              <li class="active"><a href="index.html">Docs</a></li>
              <li><a href="http://github.com/cloudera/kudu/">Repository</a></li>
              <li><a href="contributing.html">Contributions</a></li>
              <li><a href="../community.html">Community</a></li>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
</div>
++++
// end::start_nav[]

// License Header Here //
:author: Kudu Team
:imagesdir: ./images
:icons: font
:doctype: book
:backend: html5
:sectlinks:
:experimental:

++++
<div class="jumbotron">
++++

link:introduction.html[Introducing Kudu]::
  Get familiar with what sets Kudu apart.

link:quickstart.html[Getting Started With Kudu]::
  Deploy a simple proof-of-concept Kudu cluster to try it out for yourself.

link:installation.html[Installation Guide]::
  Details about all the different options for installing Kudu.

link:configuration.html[Configuring Kudu]::
  Guidelines for customizing your Kudu cluster.

link:administration.html[Administering Kudu]::
  Keeping Kudu running smoothly.

link:troubleshooting.html[Troubleshooting Kudu]::
  Guidelines for solving problems with your Kudu cluster.

link:developing.html[Developing Applications With Kudu]::
  Information about Kudu APIs and links to working example code.

link:contributing.html[Contributing to Kudu]::
  Get involved in the Kudu community.

link:style_guide.html[Kudu Style Guide]::
  Guidelines for development and documentation contributions to the Kudu project.

link:configuration_reference.html[Kudu Configuration Reference]::
  Documentation for all Kudu configuration options.

link:resources.html[Kudu Resources]::
  Further reading about Kudu, columnar data stores, and other useful material for Kudu
  users and developers.

++++
</div>
++++
