[[kudu_impala]]
= Using Impala With Kudu
:author: Kudu Team
:imagesdir: ./images
:icons: font
:toc: left
:toclevels: 3
:doctype: book
:backend: html5
:sectlinks:
:experimental:

Kudu has tight integration with Impala, allowing you to use Impala
to insert, query, update, and delete data from Kudu tablets using Impala's SQL
syntax, as an alternative to using the link:installation.html#view_api[Kudu APIs]
to build a custom Kudu application. In addition, you can use JDBC or ODBC to connect
existing or new applications written in any language, framework, or business intelligence
tool to your Kudu data, using Impala as the broker.

== Requirements and Implications

This integration relies on features that released versions of Impala do not have yet,
as of Impala 2.3, which is expected to ship in CDH 5.5. In the interim, you need
to install a fork of Impala, which this document will refer to as _Impala_Kudu_.

* You can install Impala_Kudu using parcels or packages.

* Impala_Kudu depends upon CDH 5.4 or later. To use Cloudera Manager with Impala_Kudu,
you need Cloudera Manager 5.4.3 or later.

* If you have an existing Impala instance on your cluster, you can install Impala_Kudu
alongside the existing Impala instance *if you use parcels*. The new instance does
not share configurations with the existing instance and is completely independent.
A script is provided to automate this type of installation.

* It is especially important that the cluster has adequate
unreserved RAM for the Impala_Kudu instance.

* Consider shutting down the original Impala service when testing Impala_Kudu if you
want to be sure it is not impacted.

* Before installing Impala_Kudu, you must have already installed and configured
services for HDFS, Hive, and link:installation.html[Kudu]. You may need HBase, YARN,
Sentry, and ZooKeeper services as well.


== Installing Impala_Kudu Using Cloudera Manager

If you use Cloudera Manager, you can install Impala_Kudu using
<<install_impala_kudu_parcels,parcels>> or
<<install_impala_kudu_packages,packages>>. However, if you have an existing Impala
instance, you must use parcels and you should use the instructions provided in
<<install_impala_kudu_parcels_side_by_side,procedure>>, rather than these instructions.

[install_impala_kudu_parcels]
=== Installing the Impala_Kudu Service Using Parcels

[install_impala_kudu_parcels_side_by_side]
==== Manual Installation

Manual installation of Impala_Kudu is only supported where there is no other Impala
service already running in the cluster, and when you use parcels.

. Obtain the Impala_Kudu parcel either by using the parcel repository or downloading it manually.
  * To use the parcel repository:
  ** Go to *Hosts / Parcels*.
  ** Click *Edit Settings*. Add http://repos.jenkins.cloudera.com/kimpala-nightly/parcels/latest/
      as a *Remote Parcel Repository URL*. Click *Save Changes*.
  * To download the parcel manually:
  ** Download the parcel for your operating system from
    http://repos.jenkins.cloudera.com/kimpala-nightly/parcels/latest/ and upload
    it to `/opt/cloudera/parcel-repo/` on the Cloudera Manager server.
  ** Create a SHA1 file for the parcel. Cloudera Manager expects the SHA1 to be named
    with the exact same name as the parcel, with a `.sha` ending added, and to only
    contain the SHA1 itself, not the name of the parcel.
+
----
sha1sum <name_of_parcel_file> | awk {'print $1'} > <name_of_parcel_file>.sha
----
+
. Go to *Hosts / Parcels*. Click *Check for New Parcels.* Verify that *Impala_Kudu*
is in the list.
. Download (if necessary), distribute, and activate the *Impala_Kudu* parcel.
. Add a new Impala service. This service will use the Impala_Kudu parcel.
  * Go to the cluster and click *Actions / Add a Service*.
  * Choose one host to run the Catalog Server, one to run the StateServer, and one
or more to run Impala Daemon instances. Click *Continue*.
  * Choose one or more Impala scratch directories. Click *Continue*. The Impala service
  starts. *However, the features that Impala needs in order to work with Kudu are not
  enabled yet.*
. Enable the features that allow Impala to work with Kudu.
  * Go to the new Impala service. Click *Configuration*.
  * Search for the *Impala Service Environment Advanced Configuration Snippet (Safety
  Valve)* configuration item. Add the following to the text field and save your changes: `IMPALA_NEXT=1`
  * Restart the Impala service.


==== Installation using the `deploy.py` Script

If you use parcels, Cloudera recommends using the included `deploy.py` script to
install and deploy the Impala_Kudu service into your cluster. If your cluster does
not have an existing Impala instance, the script is optional. However, if you do
have an existing Impala instance, you must use the script.

.Prerequisites
* The script depends upon the Cloudera Manager API Python bindings. Install the bindings
using `sudo pip install cm-api` (or as an unprivileged user, with the `--user`
option to `pip`), or see http://cloudera.github.io/cm_api/docs/python-client/
for more details.
* You need the following information to run the script:
** The IP address or hostname of the Cloudera Manager server.
** The cluster name, if Cloudera Manager manages multiple clusters.
** If you have an existing Impala service and want to clone its configuration, you
  need to know the name of the existing service.
** If your cluster has more than one instance of a HDFS, Hive, HBase, or other CDH
  service that this Impala_Kudu service depends upon, the name of the service this new
  Impala_Kudu service should use.
** A name for the new Impala service.
** A username and password with *Full Administrator* privileges in Cloudera Manager.
** The IP address or hostname of the host where the new Impala_Kudu service's master role
  should be deployed, if not the Cloudera Manager server.
** A comma-separated list of local (not HDFS) scratch directories which the new
Impala_Kudu service should use, if you are not cloning an existing Impala service.
* Your Cloudera Manager server needs network access to reach the parcel repository
hosted on `cloudera.com`.

.Procedure

- Run the `deploy.py` script with the following syntax to create a standalone IMPALA_KUDU
service called `IMPALA_KUDU-1` on a cluster called `Cluster 1. Exactly one HDFS, Hive,
and HBase service exist in Cluster 1, so service dependencies are not required.
+
[source,bash]
----
$ python deploy.py create IMPALA_KUDU-1 --cluster 'Cluster 1'
----
+
- If two HDFS services are available, called `HDFS-1` and `HDFS-2`, use the following
syntax to create the same `IMPALA_KUDU-1` service using `HDFS-2`. You can specify
multiple types of dependencies; use the `deploy.py create -h` command for details.
+
[source,bash]
----
$ python deploy.py create IMPALA_KUDU-1 --cluster 'Cluster 1' --hdfs_dependency HDFS-2
----
+
- Run the `deploy.py` script with the following syntax to clone an existing IMPALA
service called `IMPALA-1` to a new IMPALA_KUDU service called `IMPALA_KUDU-1`, where
Cloudera Manager only manages a single cluster:
+
[source,bash]
----
$ python deploy.py clone IMPALA_KUDU-1 IMPALA-1
----
+
- Additional parameters are available for `deploy.py`. To view them, use the `-h`
argument.  You can also use commands such as `deploy.py create -h` or
`deploy.py clone -h` to get information about additional arguments for individual operations.

- The service is created *but not started*. Review the configuration in Cloudera Manager
and start the service.

[[install_impala_kudu_packages]]
=== Installing Impala_Kudu Using Packages

Before installing Impala_Kudu packages, you need to uninstall any existing Impala
packages, using operating system utilities. For this reason, you cannot use Impala_Kudu
alongside another Impala instance if you use packages.

. Obtain the Impala_Kudu packages for your operating system from one of the following
locations:
** RHEL 6: http://repos.jenkins.cloudera.com/kimpala-nightly/redhat/6/x86_64/kimpala/
** Ubuntu Trusty: http://repos.jenkins.cloudera.com/kimpala-nightly/ubuntu/trusty/amd64/kimpala/
. Install the packages on each host which will run a role in the Impala_Kudu service,
using your operating system's utilities.
. Add a new Impala service in Cloudera Manager.
** Go to the cluster and click *Actions / Add a Service*.
** Choose one host to run the Catalog Server, one to run the Statestore, and at
  least three to run Impala Daemon instances. Click *Continue*.
** Choose one or more Impala scratch directories. Click *Continue*.
. The Impala service starts.

== Installing Impala_Kudu Using the Command Line

Before installing Impala_Kudu packages, you need to uninstall any existing Impala
packages, using operating system utilities. For this reason, you cannot use Impala_Kudu
alongside another Impala instance if you use packages.

IMPORTANT: Do not use these command-line instructions if you use Cloudera Manager.
Instead, follow <<install_impala_kudu_packages>>.

. Obtain the Impala_Kudu packages for your operating system from one of the following
locations:
** RHEL 6: http://repos.jenkins.cloudera.com/kimpala-nightly/redhat/6/x86_64/kimpala/
** Ubuntu Trusty: http://repos.jenkins.cloudera.com/kimpala-nightly/ubuntu/trusty/amd64/kimpala/
. Install the packages on each host which will run a role in the Impala_Kudu service,
using your operating system's utilities.
. Use the Impala start-up scripts to start each service on the relevant hosts:
+
----
$ sudo service impala-state-store start

$ sudo service impala-catalog start

$ sudo service impala-server start
----

== Using the Impala Shell

NOTE: This is only a small sub-set of Impala Shell functionality. For more details, see the
link:http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/impala_impala_shell.html
[Impala Shell] documentation.

Neither Kudu nor Impala need special configuration in order for you to use the Impala
Shell or the Impala API to insert, update, delete, or query Kudu data using Impala.
However, you do need to create a mapping between the Impala and Kudu tables. Kudu
provides the Impala query to map to an existing Kudu table in the web UI.

- Be sure you are using the `impala-shell` binary provided by the Impala_Kudu package,
rather than the default CDH Impala binary. The following shows how to verify this
using the `alternatives` command on a RHEL 6 host.
+
[source,bash]
----
$ sudo alternatives --display impala-shell

impala-shell - status is auto.
 link currently points to /opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.1007/bin/impala-shell
/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.1007/bin/impala-shell - priority 10
/opt/cloudera/parcels/IMPALA_KUDU-2.3.0-1.cdh5.5.0.p0.119/bin/impala-shell - priority 5
Current `best' version is /opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.1007/bin/impala-shell.

$ sudo alternatives --set impala-shell /opt/cloudera/parcels/IMPALA_KUDU-2.3.0-1.cdh5.5.0.p0.119/bin/impala-shell
----
- Start Impala Shell using the `impala-shell` command. By default, `impala-shell`
attempts to connect to the Impala daemon on `localhost` on port 21000. To connect
to a different host,, use the `-i <host:port>` option. To automatically connect to
a specific Impala database, use the `-d <database>` option. For instance, if all your
Kudu tables are in Impala in the database `impala_kudu`, use `-d impala_kudu` to use
this database.
- To quit the Impala Shell, use the following command: `quit;`

=== Internal and External Impala Tables
When creating a new Kudu table using Impala, you can create the table as an internal
table or an external table.

Internal:: An internal table is managed by Impala, and when you drop it from Impala,
the data and the table truly are dropped. When you create a new table using Impala,
it is generally a internal table.

External:: An external table (created by `CREATE EXTERNAL TABLE`) is not managed by
Impala, and dropping such a table does not drop the table from its source location
(here, Kudu). Instead, it only removes the mapping between Impala and Kudu. This is
the mode used in the syntax provided by Kudu for mapping an existing table to Impala.

See link:http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/impala_tables.html
for more information about internal and external tables.

=== Querying an Existing Kudu Table In Impala
. Go to http://kudu-master.example.com:8051/tables/, where _kudu-master.example.com_
is the address of your Kudu master.
. Click the table ID for the relevant table.
. Scroll to the bottom of the page, or search for `Impala CREATE TABLE statement`.
Copy the entire statement.
. Paste the statement into Impala. Impala now has a mapping to your Kudu table.

=== Creating a New Kudu Table From Impala
Creating a new table in Kudu from Impala is similar to mapping an existing Kudu table
to an Impala table, except that you need to write the `CREATE` statement yourself.
Use the following example as a guideline. Impala first creates the table, then creates
the mapping.

[source,sql]
----
CREATE TABLE my_first_table (
id BIGINT,
name STRING
)
TBLPROPERTIES(
  'storage_handler' = 'com.cloudera.kudu.hive.KuduStorageHandler',
  'kudu.table_name' = 'my_first_table',
  'kudu.master_addresses' = 'kudu-master.example.com:7051',
  'kudu.key_columns' = 'id'
);
----

NOTE: Impala uses a database containment model. You can create a table within a specific
scope, referred to as a _database_. To create the database, use a `CREATE DATABASE`
statement. To use the database for further Impala operations such as `CREATE TABLE`,
use the `USE` statement. For example, to create a table in a database called `impala_kudu`,
use the following statements:
+
[source,sql]
----
CREATE DATABASE impala_kudu
USE impala_kudu;
CREATE TABLE my_first_table (
id BIGINT,
name STRING
)
TBLPROPERTIES(
  'storage_handler' = 'com.cloudera.kudu.hive.KuduStorageHandler',
  'kudu.table_name' = 'my_first_table',
  'kudu.master_addresses' = 'kudu-master.example.com:7051',
  'kudu.key_columns' = 'id'
);
----
+
The `my_first_table` table is created within the `impala_kudu` database. To refer
to this database in the future, without using a specific `USE` statement, you can
refer to the table using `<database>:<table>` syntax. For example, to specify the
`my_first_table` table in database `impala_kudu`, as opposed to any other table with
the same name in another database, use `impala_kudu:my_first_table`. This also applies
to `INSERT`, `UPDATE`, `DELETE`, and `DROP` statements.

In the `CREATE TABLE` statement, the first column must be the primary key. Additionally,
the primary key can never be null when inserting or updating a row.

All properties in the `TBLPROPERTIES` subclause are required, and the `kudu.key_columns`
must contain at least one column.

=== Inserting A Row

[source,sql]
----
INSERT INTO my_first_table VALUES (99, "sarah");
----

[source,sql]
----
INSERT INTO my_first_table VALUES (1, "john"), (2, "jane"), (3, "jim");
----

=== Inserting In Bulk

In general, the Impala documentation discourages adding rows by using multiple `INSERT`
statements due to ineffiency. Exceptions to this rule are HBase and Kudu.

=== Updating a Row

[source,sql]
----
UPDATE my_first_table SET name="bob" where id = 3;
----

IMPORTANT: The `UPDATE` statement only works in Impala when the underlying
data source is Kudu.

=== Deleting a Row

[source,sql]
----
DELETE FROM my_first_table WHERE id = 3;
----

You can also delete using more complex syntax. A comma in the `FROM` sub-clause is
one way that Impala specifies a join query.
[source,sql]
----
DELETE c FROM my_second_table c, stock_symbols s WHERE c.name = s.symbol;
----

IMPORTANT: The `DELETE` statement only works in Impala when the underlying
data source is Kudu.

=== Altering Table Properties

To change the Kudu master address, change the table from internal to external or vice
versa, change the Kudu table name in the Impala mapping, you need to alter the table
properties. TBD pending KUDU-1029.

=== Dropping a Kudu Table Using Impala

- If the table was created as an internal table in Impala, using `CREATE TABLE`, the
standard `DROP TABLE` syntax drops the underlying Kudu table and all its data. If
the table was created as an external table, using `CREATE EXTERNAL TABLE`, the mapping
between Impala and Kudu is dropped, but the Kudu table is left intact, with all its
data.
+
[source,sql]
----
DROP TABLE my_first_table;
----

== What's Next?

The examples above have only explored a fraction of what you can do with Impala Shell.

- Learn about the link:http://impala.io[Impala project].
- Read the link:http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/impala.html
[Impala documentation].
- View the link:http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/impala_langref.html
[Impala SQL reference].
- Read about Impala internals or learn how to contribute to Impala on the link:https://github.com/cloudera/Impala/wiki[Impala Wiki].
- Read about the native link:installation.html#view_api[Kudu APIs].