[[quickstart]]
= Kudu Quickstart

:author: Kudu Team
:imagesdir: ./images
:icons: font
:toc: left
:toclevels: 3
:doctype: book
:backend: html5
:sectlinks:
:experimental:

This quickstart guides you through getting, installing, and starting a three-
node Kudu cluster in CDH using Cloudera Manager, putting some data into it, and
reading some data from it, without going into details. For more in-depth information, see
link:installation.html[Kudu Installation].

[[quickstart_vm]]
== Kudu Quickstart VM
You can get started even quicker! Check out the Quickstart VM  at
https://github.com/cloudera/kudu-examples/ and start using Kudu in minutes.

== Prerequisites
* A Cloudera Manager cluster with the <<how_many_hosts,right number of hosts>>.
* Write access to the `/opt/cloudera/csd` directory on the Cloudera Manager server.

[[how_many_hosts]]
// == How Many Hosts?
// .How many masters?
// - If you run three masters and one fails, the other two can continue. If the leader
// failed, one of the other masters can become the leader.
// - If you run two masters and one fails, the other master cannot achieve a
//  quorum to become leader. With no lead master, your cluster will not function
//  correctly.
//- You must have an odd number of masters, to avoid a "split brain" scenario
//  where half the masters are on either side of the partition and neither side
//  has the majority.

//.How many tablet servers?
== How Many Tablet Servers?
- If you run three tablet servers and one fails, the other two can continue. If
  the leader failed, one of the other tablet servers can become the
  leader.
- If you run two tablet servers and one fails, the other tablet server cannot
  achieve a quorum to become leader. With no leader, no writes can occur.
- You must have an odd number of tablet servers, to avoid a "split brain"
  scenario where half the tablet servers are on either side of the partition
  and neither side has the majority.

One host can run both master and tablet server processes.

== Install Kudu Using Parcels

include::installation.adoc[tags=quickstart_parcels]



[[qs_access_web_ui]]
== Access the Web UIs

In addition to the Kudu service in Cloudera Manager, each of the masters and tablet
servers exposes a Web UI. By default, the web UI binds to port `8051` for masters,
and `8050` for tablet servers, on interface
`0.0.0.0`.

From any host's Web UI, you can access the Web UIs for each other master and
tablet server, as well as logs, memory reports, and a JSON dump of metrics.
Explore the Web UIs to get an idea of what you might find.

== Load Some Data

TBD

== Retrieve Some Data

TBD

== Test Fault Tolerance

If you are running at least three masters and at least three tablet servers are
serving each tablet, you can stop any master or tablet server and the Kudu
cluster will recover. See <<how_many_hosts>>. If all masters disappear, tablet
servers will continue to serve cached data. If too many tablet servers disappear and
a quorum cannot be achieved, writes to that tablet will fail.

To stop a process running in the foreground, interrupt it with Ctrl-C.
Otherwise, kill the process using operating system utilities. Monitor the log
files and the Web UIs to see what happens when a failure is detected, and what
happens when a new master or tablet server joins the cluster.


== Next Steps
- link:quickstart.html[Get Started With Kudu]
- link:installation.html[Kudu Installation Guide]

