# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# We need to use versions that can run on CentOS 7, which ships Ruby 2.0.0.
ruby '>= 2.0.0'

source 'https://rubygems.org'

gem 'thread_safe'
gem 'redcarpet'
gem 'jekyll'
gem 'therubyracer' # V8 runtime installer for Jekyll.
gem 'ref'
gem 'json'
gem 'rdoc'
gem 'yajl-ruby', '>= 1.3.1' # Due to CVE-2017-16516.
gem 'libv8', '>= 3.16.14.14' # Needed for macOS.

gem 'asciidoctor'
gem 'tilt'
